name: Free-RDP-RemoteIt

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest

    steps:
      - name: Enable RDP
        run: |
          Set-ItemProperty HKLM:\System\CurrentControlSet\Control\Terminal Server -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Install Remote.it
        run: |
          Invoke-WebRequest -Uri https://downloads.remote.it/cli/remoteit-windows.zip -OutFile remoteit.zip
          Expand-Archive remoteit.zip -DestinationPath .\remoteit
          cd remoteit
          .\remoteit.exe connect --rdp runneradmin P@ssw0rd!
