name: FreeRDP-Windows

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download and Run RDP Script
      shell: powershell
      run: |
        iwr -useb https://raw.githubusercontent.com/lshpanther/FreeRDP/main/RDP.ps1 | iex
