# .github/workflows/free-rdp.yml
name: Free RDP Tunnel

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    env:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    steps:
      - name: Download ngrok
        run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

      - name: Unzip ngrok
        run: Expand-Archive ngrok.zip -DestinationPath ./ngrok

      - name: Enable RDP
        run: |
          Set-ItemProperty HKLM:\System\CurrentControlSet\Control\Terminal Server -Name fDenyTSConnections -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

      - name: Set password for runneradmin
        run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)

      - name: Start ngrok TCP tunnel
        run: .\ngrok\ngrok.exe tcp 3389 --log=stdout
